### ISSUE TITLE
Vertaling contact formulier. 

### ISSUE THREAD

**Issue by Tjoosten** [CPSB/Skeleton-project#43]

**Comment by Tjoosten** [comment]
@alfamongrel Kun jij ervoor zorgen- dat de waardes achter ``=>` vertaald worden in het engels en frans?

FILE: https://github.com/CPSB/Skeleton-project/blob/master/resources/lang/nl/contact.php

**Comment by alfamongrel** [comment]
ok in proces

**Comment by alfamongrel** [comment]
Nederlands  -> frans
Insturen 
envoyer

Reset
remise

Heb je vragen? Aarzel dan niet om ons te contacteren.
Vous avez des questions?
N’hésitez pas à nous contacter

We hebben je vraag ontvangen.
Nous avons reçu votre demande. 

We nemen spoedig contact met je op!
Nous communiquerons avec vous! 

Uw achternaam => votre nom
Uw voornaam => votre prénom
Uw email adres => Votre adresse e-mail
Onderwerp => sujet
Uw bericht => votre message


Nederlands – Engels

Insturen 
Submit

Reset	
Reset

Heb je vragen? Aarzel dan niet om ons te contacteren.
Do you have questions? Do not hesitate to contact us.

We hebben je vraag goed ontvangen.
We received your question well

We nemen spoedig contact met je op!
We will contact you soon!
	
Uw achternaam 	=>Your last name
Uw voornaam	=> Your first name
Uw email adres	=> Your email address
Onderwerp		=> Topic
Uw bericht		=> Your message

**Comment by alfamongrel** [comment]
nog niet sluiten er zitten fouten in het frans

**Comment by Tjoosten** [comment]
Was ik nog niet van plan :)

**Comment by Tjoosten** [comment]
@alfamongrel Status? 

@Tjoosten. Moet een patch file van gemaakt worden. Zodat we een apply kounnen uitvoeren op andere platformen.
